apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playlist-recommender
spec:
  project: default
  source:
    repoURL: "https://github.com/myrepo/playlist-recommender"
    path: "k8s"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

