apiVersion: v1
kind: Service
metadata:
  name: playlist-api-service
spec:
  selector:
    app: playlist-api
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 52011  
  type: NodePort  
