apiVersion: batch/v1
kind: Job  # ✅ 这里改成 Job
metadata:
  name: playlist-ml
spec:
  template:
    metadata:
      labels:
        app: playlist-ml
    spec:
      restartPolicy: Never  # ✅ 只允许 Job 使用 restartPolicy: Never
      containers:
      - name: playlist-ml
        image: zzy0110/playlist-ml:latest
        command: ["python", "/app/train_model.py"]
        volumeMounts:
        - name: spotify-dataset
          mountPath: /home/datasets/spotify  # ✅ 把数据集挂载到容器内部
      volumes:
      - name: spotify-dataset
        hostPath:
          path: /home/datasets/spotify  # ✅ 挂载实际的数据集路径
          type: Directory

